<?php
$books = array(
    array("bookname" => "HTML and CSS",
            "author" => "Jon Duckett",
            "price" => "17.19$",
            "description" => "Every day, more and more people want to learn some HTML and CSS.",
            "image" => "HTMLandCSS_Duckett.jpg"),
    array("bookname" => "HTML5",
            "author" => "Matthew MacDonald",
            "price" => "27.65$",
            "description" => "HTML5 is more than a markup language-it's a collection of several independent web...",
            "image" => "HTML5TheMissing_MacDonald.jpg"),
    array("bookname" => "Head First HTML5 Programming",
            "author" => "Eric Freeman,Elisabeth Robson",
            "price" => "35.35$",
            "description" => "HTML has been on a wild ride. Sure, HTML started as mere markup language..",
            "image" => "HeadFirstHTML5.jpg"),
    array("bookname" => "Head First JavaScript Programming",
            "author" => "Eric Freeman,Elisabeth Robson",
            "price" => "37.60$",
            "description" => "This brain-friendly quide teaches you everything from JS language fundament.",
            "image" => "HeadFirstJavaScript.jpg"),
    array("bookname" => "jQuery in Action",
            "author" => "Bear Bibeault, Yehuda Katz",
            "price" => "32.12$",
            "description" => "A really good web development framework anticipates your needs.",
            "image" => "JQueryInAction.jpg"));
?>